model_colors:
  transfer_model: "tab:blue"
  physical_model: "tab:orange"
  source_model: "tab:green"
  target_model: "tab:red"
  standard_model: "tab:gray"

models:
  - ["transfer_model_testday_metrics.csv", "Transfer Learning", "transfer_model"]
  - ["physical_model_testday_metrics.csv", "Physical Model", "physical_model"]
  - ["source_model_testday_metrics.csv", "Source Model", "source_model"]
  - ["target_model_testday_metrics.csv", "Target Model", "target_model"]

models_all:
  - ["transfer_model_all_metrics.csv", "Transfer Learning", "transfer_model"]
  - ["physical_model_all_metrics.csv", "Physical Model", "physical_model"]
  - ["source_model_all_metrics.csv", "Source Model", "source_model"]
  - ["target_model_all_metrics.csv", "Target Model", "target_model"]

transfer_csv: "transfer_model_testday_metrics.csv"
